name: Build and Export Docker Images on Tag

on:
  push:
    tags:
      - 'v*'  # triggers on tag pushes like v1.0.0

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: atam
            dockerfile: atam/Atam.Dockerfile
            context: atam
            name_upper: ATAM
          - name: opsys
            dockerfile: OperatingSystems/OpSys.Dockerfile
            context: OperatingSystems
            name_upper: OS

    env:
      OP_SYS_TAG: ${{ github.ref_name }}
      COMMIT_TAG: ${{ github.sha }}
      # ATAM secrets
      STUDENT_PASS_ATAM: ${{ secrets.STUDENT_PASS_ATAM }}
      STUDENT_GROUP_NAME_ATAM: ${{ secrets.STUDENT_GROUP_NAME_ATAM }}
      STUDENT_GROUP_UID_ATAM: ${{ secrets.STUDENT_GROUP_UID_ATAM }}
      STUDENT_UID_ATAM: ${{ secrets.STUDENT_UID_ATAM }}
      # OS secrets
      STUDENT_PASS_OS: ${{ secrets.STUDENT_PASS_OS }}
      STUDENT_GROUP_NAME_OS: ${{ secrets.STUDENT_GROUP_NAME_OS }}
      STUDENT_GROUP_UID_OS: ${{ secrets.STUDENT_GROUP_UID_OS }}
      STUDENT_UID_OS: ${{ secrets.STUDENT_UID_OS }}
      # GitHub token for release upload
      GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

    permissions:
      contents: write  # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Buildx with docker-container driver for caching support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Create and use custom builder
        run: |
          docker buildx create --name mybuilder --driver docker-container --use
          docker buildx inspect --bootstrap

      # Restore Docker layer cache (global key)
      - name: Restore Docker layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-global-cache
          restore-keys: |
            docker-global-cache

      - name: Build ${{ matrix.target.name }} image
        run: |
          docker buildx build \
            --builder mybuilder \
            --platform linux/amd64 \
            --secret id=student_pass_${{ matrix.target.name }},env=STUDENT_PASS_${{ matrix.target.name_upper }} \
            --secret id=student_group_uid_${{ matrix.target.name }},env=STUDENT_GROUP_UID_${{ matrix.target.name_upper }} \
            --secret id=student_group_name_${{ matrix.target.name }},env=STUDENT_GROUP_NAME_${{ matrix.target.name_upper }} \
            --secret id=student_uid_${{ matrix.target.name }},env=STUDENT_UID_${{ matrix.target.name_upper }} \
            -t ${{ matrix.target.name }}:${{ env.COMMIT_TAG }} \
            -f ${{ matrix.target.dockerfile }} ${{ matrix.target.context }} \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            --load

      # Save image tarballs
      - name: Save ${{ matrix.target.name }} image tarball
        run: |
          docker save ${{ matrix.target.name }}:${{ env.COMMIT_TAG }} -o ${{ matrix.target.name }}Ubuntu-image-${OP_SYS_TAG}.tar

      # Export rootfs tarballs from containers
      - name: Export ${{ matrix.target.name }} rootfs tarball
        run: |
          container_id=$(docker run -t -d --name ${{ matrix.target.name }}Container ${{ matrix.target.name }}:${{ env.COMMIT_TAG }} /bin/bash)
          docker export --output=${{ matrix.target.name }}Ubuntu-rootfs-${OP_SYS_TAG}.tar $container_id

      # Compress all tarballs
      - name: Compress ${{ matrix.target.name }} tarballs
        run: |
          gzip -9 ${{ matrix.target.name }}Ubuntu-image-${OP_SYS_TAG}.tar
          gzip -9 ${{ matrix.target.name }}Ubuntu-rootfs-${OP_SYS_TAG}.tar

      # Upload tarballs as artifacts
      - name: Upload ${{ matrix.target.name }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Docker-${{ matrix.target.name }}-${{ env.OP_SYS_TAG }}
          path: |
            ${{ matrix.target.name }}Ubuntu-image-${{ env.OP_SYS_TAG }}.tar.gz
            ${{ matrix.target.name }}Ubuntu-rootfs-${{ env.OP_SYS_TAG }}.tar.gz

      # Upload tarballs to GitHub Release
      - name: Upload ${{ matrix.target.name }} to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.target.name }}Ubuntu-image-${{ env.OP_SYS_TAG }}.tar.gz
            ${{ matrix.target.name }}Ubuntu-rootfs-${{ env.OP_SYS_TAG }}.tar.gz

      # Save Docker layer cache
      - name: Save Docker layer cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: /tmp/.buildx-cache
          key: docker-global-cache
