name: Build and Export Docker Images and Containers on Tag

on:
  push:
    tags:
      - 'v*'  # triggers on tag pushes like v1.0.0

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    env:
      OP_SYS_TAG: ${{ github.ref_name }}
      COMMIT_TAG: ${{ github.sha }}

    permissions:
      contents: write  # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # --- Build and export atam-build image ---
      - name: Build and save Atam image to tar
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_atam,env=STUDENT_PASS_ATAM \
            --secret id=student_uid_atam,env=STUDENT_UID_ATAM \
            -f atam/Atam.Dockerfile atam \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --output type=docker,dest=AtamUbuntu-image.tar
        env:
          STUDENT_PASS_ATAM: ${{ secrets.STUDENT_PASS_ATAM }}
          STUDENT_UID_ATAM: ${{ secrets.STUDENT_UID_ATAM }}

      # --- Run and export Atam container ---
      - name: Run and export Atam container
        run: |
          docker load -i AtamUbuntu-image.tar
          container_id=$(docker run -t -d --name AtamUbuntuContainer atam /bin/bash)
          docker export --output=AtamUbuntu-container.tar $container_id

      # --- Build and export opsys-build image ---
      - name: Build and save OpSys image to tar
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_os,env=STUDENT_PASS_OS \
            --secret id=student_uid_os,env=STUDENT_UID_OS \
            -f OperatingSystems/OpSys.Dockerfile OperatingSystems \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --output type=docker,dest=OpSysUbuntu-image.tar
        env:
          STUDENT_PASS_OS: ${{ secrets.STUDENT_PASS_OS }}
          STUDENT_UID_OS: ${{ secrets.STUDENT_UID_OS }}

      # --- Run and export OpSys container ---
      - name: Run and export OpSys container
        run: |
          docker load -i OpSysUbuntu-image.tar
          container_id=$(docker run -t -d --name OpSysUbuntuContainer opsys /bin/bash)
          docker export --output=OpSysUbuntu-container.tar $container_id

      # --- Upload all tarballs to GitHub Release ---
      - name: Upload all tars to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            AtamUbuntu-image.tar
            AtamUbuntu-container.tar
            OpSysUbuntu-image.tar
            OpSysUbuntu-container.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
