name: Build, Export, and Push Docker Images on Tag

on:
  push:
    tags:
      - 'v*'  # runs on tags like v1.0.0, v2.1.3, etc

jobs:
  build-export-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
      OP_SYS_TAG: ${{ github.ref_name }}
      COMMIT_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # --- Build atam-build image ---
      - name: Build atam-build image
          # --load \
          # --push
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_atam,env=STUDENT_PASS_ATAM \
            --secret id=student_uid_atam,env=STUDENT_UID_ATAM \
            -t $DOCKERHUB_USER/atam-build:$OP_SYS_TAG \
            -t $DOCKERHUB_USER/atam-build:$COMMIT_TAG \
            -f atam/Atam.Dockerfile atam \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --load
        env:
          STUDENT_PASS_ATAM: ${{ secrets.STUDENT_PASS_ATAM }}
          STUDENT_UID_ATAM: ${{ secrets.STUDENT_UID_ATAM }}

      # --- Build opsys-build image ---
      - name: Build opsys-build image
          # --load \
          # --push
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_os,env=STUDENT_PASS_OS \
            --secret id=student_uid_os,env=STUDENT_UID_OS \
            -t $DOCKERHUB_USER/opsys-build:$OP_SYS_TAG \
            -t $DOCKERHUB_USER/opsys-build:$COMMIT_TAG \
            -f OperatingSystems/OpSys.Dockerfile OperatingSystems \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --load
        env:
          STUDENT_PASS_OS: ${{ secrets.STUDENT_PASS_OS }}
          STUDENT_UID_OS: ${{ secrets.STUDENT_UID_OS }}

      # --- Run and export AtamUbuntu container ---
      - name: Run and export AtamUbuntu container
        run: |
          container_id=$(docker run -t -d --name AtamUbuntu $DOCKERHUB_USER/atam-build:$COMMIT_TAG /bin/bash)
          docker export --output=AtamUbuntu.tar $container_id

      # --- Run and export OpSysUbuntu container ---
      - name: Run and export OpSysUbuntu container
        run: |
          container_id=$(docker run -t -d --name OpSysUbuntu $DOCKERHUB_USER/opsys-build:$COMMIT_TAG /bin/bash)
          docker export --output=OpSysUbuntu.tar $container_id

      # --- Upload AtamUbuntu tarball ---
      - name: Upload AtamUbuntu tarball
        uses: actions/upload-artifact@v4
        with:
          name: AtamUbuntu-Tarball
          path: AtamUbuntu.tar

      # --- Upload OpSysUbuntu tarball ---
      - name: Upload OpSysUbuntu tarball
        uses: actions/upload-artifact@v4
        with:
          name: OpSysUbuntu-Tarball
          path: OpSysUbuntu.tar
