name: Build and Export Docker Images on Tag

on:
  push:
    tags:
      - 'v*'  # triggers on tag pushes like v1.0.0

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    env:
      OP_SYS_TAG: ${{ github.ref_name }}
      COMMIT_TAG: ${{ github.sha }}

    permissions:
      contents: write  # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Restore Docker Layer Cache ---
      - name: Restore Docker layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-global
          restore-keys: |
            ${{ runner.os }}-buildx-

      # --- Build atam image ---
      - name: Build atam image
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_atam,env=STUDENT_PASS_ATAM \
            --secret id=student_uid_atam,env=STUDENT_UID_ATAM \
            -t atam:$COMMIT_TAG \
            -f atam/Atam.Dockerfile atam \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            --load
        env:
          STUDENT_PASS_ATAM: ${{ secrets.STUDENT_PASS_ATAM }}
          STUDENT_UID_ATAM: ${{ secrets.STUDENT_UID_ATAM }}

      # --- Build opsys image ---
      - name: Build opsys image
        run: |
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --secret id=student_pass_os,env=STUDENT_PASS_OS \
            --secret id=student_uid_os,env=STUDENT_UID_OS \
            -t opsys:$COMMIT_TAG \
            -f OperatingSystems/OpSys.Dockerfile OperatingSystems \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            --load
        env:
          STUDENT_PASS_OS: ${{ secrets.STUDENT_PASS_OS }}
          STUDENT_UID_OS: ${{ secrets.STUDENT_UID_OS }}

      # --- Save images to tar files ---
      - name: Save images to tar
        run: |
          docker save atam:$COMMIT_TAG -o AtamUbuntu-${OP_SYS_TAG}.tar
          docker save opsys:$COMMIT_TAG -o OpSysUbuntu-${OP_SYS_TAG}.tar

      # --- Compress tarballs ---
      - name: Compress tarballs
        run: |
          gzip -9 AtamUbuntu-${OP_SYS_TAG}.tar
          gzip -9 OpSysUbuntu-${OP_SYS_TAG}.tar

      # --- Upload tarballs to GitHub artifacts ---
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Docker-Images-${{ env.OP_SYS_TAG }}
          path: |
            AtamUbuntu-${{ env.OP_SYS_TAG }}.tar.gz
            OpSysUbuntu-${{ env.OP_SYS_TAG }}.tar.gz

      # --- Upload tarballs to GitHub Release ---
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AtamUbuntu-${{ env.OP_SYS_TAG }}.tar.gz
            OpSysUbuntu-${{ env.OP_SYS_TAG }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      # --- Save Docker Layer Cache ---
      - name: Save Docker layer cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-global
